# Generated by Django 5.2.7 on 2025-11-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do produto', max_length=100, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Informe o Preço Unitario em Reais do Produto', max_digits=8, verbose_name='Preço de Venda')),
                ('estoque', models.PositiveIntegerField(default=0, help_text='Quantidade de produtos em estoque', verbose_name='quantidade_em_estoque')),
                ('ativo', models.BooleanField(default=True, help_text='Marque-se o produto que está ativo', verbose_name='Disponivel para Venda')),
            ],
            options={
                'verbose_name': ('Produto',),
                'verbose_name_plural': ('Produtos'),
                'ordering': ['nome'],
            },
        ),
    ]
